# Custom Language File for Launcher Customizer

[ejs.app]
title = "FoxDeath Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur FoxDeath"
welcomeDescription = "S'amusez c'est surtout ça !"
welcomeDescCTA = "et s'amusez aussi XD"
