[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Username"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NEWS"
launchButton = "PLAY"
launchButtonPlaceholder = "&#8226; Aucun serveur selectionné"
launchDetails = "Attendez..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Attente de News.."
newsErrorFailedSpan = "Erreur pour charger les News"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Pas de News"